### PR TITLE
Support for Ubuntu 12.04

### PR DESCRIPTION
**Pull request by vincentbernat**
This also contains fixes for Debian as I believe the same configuration should be applied to Debian. To be able to support correctly Debian 7 and Ubuntu 12.04, a new parameter to tell which identity conserver-server will run is used.

### CODE REVIEW

**Comment by faxm0dem** [comment]
Thanks a lot for this contribution! I'll test it ASAP!

**Comment by faxm0dem** [comment]
I'm very busy at the moment please indulge me I'll merge ASAP

**Comment by samplerr** [comment]
All right, no time to test. merged!

**Comment by faxm0dem** [comment]
No time to test this unfortunately.
I'll have to trust you on this :)

**Comment by vincentbernat** [comment]
I hope I'll be worthy of it! :) Mention me in any issue that may arise.

**Pull request merged**
